Repository mainmatter/ember-promise-modals, pull requests merged in 2020-04, with the labels that each got.

#139 Drop Support for Node.js 8
  .travis.yml
  README.md
  package.json
Labels: breaking

#140 Remove obsolete `ember-cli-htmlbars-inline-precompile` dependency
  package.json
Labels: dependencies

#141 Use GitHub Actions for CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .travis.yml
Labels: internal

#142 Convert `ember-animated` to a peer dependency
  README.md
  package.json
Labels: breaking

#143 CI: Add scenarios for Ember v3.12 and v3.16
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#80 Update README
  README.md
Labels: documentation
