Repository mainmatter/ember-promise-modals, pull requests merged in 2021-07, with the labels that each got.

#407 upgrade to ember-qunit v5
  package.json
  tests/index.html
  tests/test-helper.js
  yarn.lock
Labels: internal

#148 Replace ember-animated with CSS animations
  .github/epm.svg
  MIGRATION.md
  README.md
  addon-test-support/index.js
  addon/components/modal.js
  addon/modal.js
  addon/services/modals.js
  addon/styles/ember-promise-modals.css
  addon/templates/components/modal-container.hbs
  addon/templates/components/modal.hbs
  config/ember-try.js
  index.js
  package.json
  tests/application/basics-test.js
  tests/dummy/app/controllers/application.js
  tests/dummy/app/services/modal.js
  tests/dummy/app/styles/app.css
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/modal1.hbs
  tests/integration/components/modal-container-test.js
  tests/unit/services/modals-test.js
  yarn.lock
Labels: breaking, enhancement

#413 use babel-eslint as eslint parser
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#412 fix backdrop not animating immediately after the last modal is closed
  addon/modal.js
  addon/services/modals.js
  config/ember-try.js
  tests/unit/services/modals-test.js
Labels: bug

#417 Delete unused modal service file from dummy app
  tests/dummy/app/services/modal.js
Labels: internal

#420 explicitly specify animation delay and duration as separate to make sure they're properly used by the browser
  addon/styles/ember-promise-modals.css
Labels: bug

#421 add optional onAnimationModalOutEnd hook
  README.md
  addon/modal.js
  tests/unit/services/modals-test.js
Labels: enhancement

#422 fix promsie-modals from breaking when used in another addon instead of an app
  index.js
Labels: bug
