Repository mainmatter/ember-promise-modals, pull requests merged in 2022-02, with the labels that each got.

#436 Embroider optimized compatibility
  .github/workflows/ci.yml
  README.md
  addon/templates/components/modal.hbs
  config/ember-try.js
  ember-cli-build.js
  package.json
  tests/dummy/app/components/modal1.js
  tests/dummy/app/components/modal2.js
  tests/dummy/app/controllers/application.js
  yarn.lock
Labels: enhancement

#530 Internal: Extend and apply prettier configuration
  .prettierignore
  .prettierrc.js
  CONTRIBUTING.md
  MIGRATION.md
  README.md
  package.json
Labels: internal

#502 Provide additional documentation for the Modal class and ModalOptions
  README.md
  addon/modal.js
  addon/services/modals.js
Labels: documentation

#477 Replace Yarn with pnpm
  .github/workflows/ci.yml
  CONTRIBUTING.md
  config/ember-try.js
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: internal

#531 Update dependencies
  package.json
  pnpm-lock.yaml
  tests/dummy/app/styles/app.css
  tests/dummy/app/templates/application.hbs
Labels: dependencies

#533 Legacy: Downgrade native class to Ember.Object
  README.md
  addon/modal.js
  addon/services/modals.js
  config/ember-try.js
Labels: enhancement

#549 Enhance focus trap configuration
  README.md
  addon/components/modal.js
  addon/services/modals.js
  tests/application/basics-test.js
  tests/integration/configuration/focus-trap-test.js
Labels: enhancement
